### ISSUE TITLE
Export every types & export RedisStore as a named export

### ISSUE THREAD

**Issue by tdislay** [ctkc/fastify-session-redis-store#1]
**Is your feature request related to a problem? Please describe.**
I need to import some types from your library (`RedisStoreOptions`). Do you think we could exports every types / interfaces ?

**Describe the solution you'd like**
Add `export` in front of every types and interfaces :grin:.

Also, I think it would be a good idea to export `RedisStore` as a named export (e.g. `export class RedisStore {...}`) in addition to the actual default export.
Named exports are better for tree-shaking and for DX.

Thanks for your work

**Comment by ctkc** [comment]
@tdislay Thank you for the suggestion. It is now available in `v7.1.1`
